import tw from "twin.macro";

export const Column = tw.div`col-span-1`;
export const DeveloperGrid = tw.div`grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4`;
export const Developers = tw.div`text-base`;
export const FooterStyles = tw.footer`bg-black w-full text-center`;
export const GrayText = tw.div`text-gray-700`;
export const LayOutGrid = tw.div`grid grid-cols-1 sm:grid-cols-2 gap-x-4`;
export const Main = tw.div`flex items-center justify-center min-h-screen py-8`;
export const MainContent = tw.div`flex items-center justify-center min-h-screen py-8`;
export const Title = tw.h1`text-center text-black font-bold text-xl mb-2`;
export const WhiteContainer = tw.div`bg-white mt-24 p-8 shadow-lg transform translate-y-20`;
export const PrimarySection = tw.section`z-10 bg-gray-50`;
export const CenteredContent = tw.div`h-screen bg-gray-200 w-full flex justify-center items-center`;
export const Container = tw.div`container`;
export const Positioning = tw.div`absolute top-0 left-0 flex items-center justify-between w-full h-full space-x-5 -z-10 md:space-x-8 lg:space-x-14`;
export const Oops = tw.h4`mb-3 text-[22px] font-semibold leading-tight text-black`;
export const Four0Four = tw.h2`mb-2 text-[50px] font-bold leading-none text-black sm:text-[80px] md:text-[100px]`;
export const Deleted = tw.p`mb-8 text-lg text-black`;
export const GoHomeLink = tw.a`inline-block px-8 py-3 text-base font-semibold text-center text-black transition border border-white rounded-lg hover:bg-white hover:font-normal`;
export const Flexed = tw.div`flex -mx-4`;
export const PaddedFull = tw.div`w-full px-4`;
export const TextCentered = tw.div`mx-auto text-center`;
